/**
 * Three-dimensional puzzles built on the four-dimensional engine.
 *
 * These are the checks that decide whether the whole idea works. The geometry comes from the
 * unmodified original; the twist axes are generated by the exporter, because the original wraps its
 * grip construction in `if(nDims == 4)`. If that construction is wrong, it will show up here as a
 * permutation that is not a bijection or an order-4 twist that does not return to the start.
 *
 * See docs/three-d.md.
 */

import { describe, expect, it } from 'vitest';

import { loadGeometry } from './fixtures.js';
import { applyTwist, isValidTwist, numSlicesForGrip, permutationFor } from '../src/twist.js';
import { isSolved, solvedState, stateHash } from '../src/state.js';
import { gripForPick, numColorsForCubie } from '../src/grips.js';

/** What the original reports for these, measured before any of this was written. */
const PUZZLES = [
  // `perFace` is the element count of one facet: a square has 4 vertices, 4 edges and itself; a
  // pentagon 5, 5 and itself. `order` is the face turn — 90° on a cube, 72° on a dodecahedron.
  { id: '{4,3} 2', file: '4-3_2', cubies: 8, stickers: 24, order: 4, slices: 2, perFace: 9 },
  { id: '{4,3} 3', file: '4-3_3', cubies: 26, stickers: 54, order: 4, slices: 3, perFace: 9 },
  { id: '{4,3} 4', file: '4-3_4', cubies: 56, stickers: 96, order: 4, slices: 4, perFace: 9 },
  { id: '{4,3} 5', file: '4-3_5', cubies: 98, stickers: 150, order: 4, slices: 5, perFace: 9 },
  { id: '{4,3} 7', file: '4-3_7', cubies: 218, stickers: 294, order: 4, slices: 7, perFace: 9 },
  { id: '{5,3} 3', file: '5-3_3', cubies: 62, stickers: 132, order: 5, slices: 3, perFace: 11 },
] as const;

describe.each(PUZZLES)('$id', (puzzle) => {
  const geo = loadGeometry(puzzle.file);

  it('is three-dimensional and the size the original says', () => {
    expect(geo.nDims).toBe(3);
    expect(geo.nStickers).toBe(puzzle.stickers);
    expect(new Set(geo.sticker2cubie).size).toBe(puzzle.cubies);
  });

  it('has one axis per (face, element) pair, as 4D has one per (cell, element)', () => {
    expect(geo.nGrips).toBe(geo.nFaces * puzzle.perFace);
    const orders = { 0: new Set<number>(), 1: new Set<number>(), 2: new Set<number>() };
    for (let g = 0; g < geo.nGrips; ++g) {
      expect(geo.grip2face[g], `grip ${g} must name the face its slices are measured from`)
        .toBeGreaterThanOrEqual(0);
      orders[geo.gripDims[g] as 0 | 1 | 2].add(geo.gripSymmetryOrders[g]);
    }
    // Vertices turn by a third, edges by a half, and a face by its own gonality.
    expect([...orders[0]]).toEqual([3]);
    expect([...orders[1]]).toEqual([2]);
    expect([...orders[2]]).toEqual([puzzle.order]);
  });

  it('sends each kind of sticker to the axis its colour count implies', () => {
    // The whole reason for a 3D puzzle on this engine: the pick heuristic is the interface being
    // taught, and it has to behave here exactly as it does on the hypercube. See docs/three-d.md §5.
    const wanted: Record<number, number> = { 3: 3, 2: 2, 1: puzzle.order };
    for (let s = 0; s < geo.nStickers; ++s) {
      const colours = numColorsForCubie(geo, geo.sticker2cubie[s]);
      const { gripIndex } = gripForPick(geo, s, 0);
      if (wanted[colours] === undefined) continue;
      expect(gripIndex, `sticker ${s} (${colours} colours) resolves to no axis`).toBeGreaterThanOrEqual(0);
      expect(geo.gripDims[gripIndex], `sticker ${s} axis dimension`).toBe(3 - colours);
      expect(geo.gripSymmetryOrders[gripIndex], `sticker ${s} turn order`).toBe(wanted[colours]);
      expect(numSlicesForGrip(geo, gripIndex), `sticker ${s} layers`).toBe(puzzle.slices);
    }
  });

  it('gives every sticker a private, contiguous run of vertices', () => {
    // The invariant the asset's one-byte local indices depend on, which 3D only satisfies because
    // the exporter expands the shared surface mesh. See docs/three-d.md §8.
    let expected = 0;
    for (let s = 0; s < geo.nStickers; ++s) {
      expect(geo.stickerVertBegin[s], `sticker ${s} start`).toBe(expected);
      expect(geo.stickerVertCount[s]).toBeGreaterThan(0);
      expected += geo.stickerVertCount[s];
    }
    expect(expected).toBe(geo.nVerts);
  });

  it('starts solved', () => {
    expect(isSolved(geo, solvedState(geo))).toBe(true);
  });

  it('offers the expected number of layers on every axis', () => {
    // A corner turn can take one layer or all of them, exactly as a face turn can.
    for (let g = 0; g < geo.nGrips; ++g) {
      expect(numSlicesForGrip(geo, g), `grip ${g}`).toBe(puzzle.slices);
    }
  });

  it('lets only a face axis turn one layer', () => {
    // The one thing that does not carry over from four dimensions. See isValidTwist.
    for (let g = 0; g < geo.nGrips; ++g) {
      const all = (1 << numSlicesForGrip(geo, g)) - 1;
      const facet = geo.gripDims[g] === geo.nDims - 1;
      expect(isValidTwist(geo, g, all), `grip ${g} whole-solid`).toBe(true);
      expect(isValidTwist(geo, g, 1), `grip ${g} single layer`).toBe(facet);
    }
  });

  it('every legal permutation is a bijection', () => {
    // The canary. The fuzzy point hash uses absolute epsilons, so a wrong twist matrix — or a
    // vertex expansion that moved a sticker — makes lookups miss, and two slots end up reading the
    // same source. Illegal combinations are excluded by isValidTwist, which is where the rule that
    // a corner axis can only turn the whole solid lives.
    for (let g = 0; g < geo.nGrips; ++g) {
      for (let mask = 1; mask < 1 << numSlicesForGrip(geo, g); ++mask) {
        if (!isValidTwist(geo, g, mask)) continue;
        for (const dir of [1, -1] as const) {
          const perm = permutationFor(geo, g, dir, mask);
          const seen = new Uint8Array(geo.nStickers);
          for (const src of perm) seen[src] = 1;
          const missing = seen.indexOf(0);
          expect(missing, `grip ${g} dir ${dir} mask ${mask} never yields sticker ${missing}`).toBe(
            -1,
          );
        }
      }
    }
  });

  it('applying a turn its own order many times returns to the start', () => {
    // 120° three times for a corner, 180° twice for an edge, 90° four times for a face. Corners and
    // edges turn the whole solid, so they are exercised with every layer selected.
    const start = solvedState(geo);
    for (let g = 0; g < geo.nGrips; ++g) {
      const state = Int32Array.from(start);
      const mask =
        geo.gripDims[g] === geo.nDims - 1 ? 1 : (1 << numSlicesForGrip(geo, g)) - 1;
      for (let i = 0; i < geo.gripSymmetryOrders[g]; ++i) applyTwist(geo, state, g, 1, mask);
      expect(stateHash(state), `grip ${g}`).toBe(stateHash(start));
    }
  });

  it('a turn followed by its inverse is the identity', () => {
    const start = solvedState(geo);
    for (let g = 0; g < geo.nGrips; ++g) {
      for (let mask = 1; mask < 1 << numSlicesForGrip(geo, g); ++mask) {
        if (!isValidTwist(geo, g, mask)) continue;
        const state = Int32Array.from(start);
        applyTwist(geo, state, g, 1, mask);
        applyTwist(geo, state, g, -1, mask);
        expect(stateHash(state), `grip ${g} mask ${mask}`).toBe(stateHash(start));
      }
    }
  });

  it('conserves the colour census', () => {
    const state = solvedState(geo);
    const before = new Map<number, number>();
    for (const c of state) before.set(c, (before.get(c) ?? 0) + 1);
    for (let g = 0; g < geo.nGrips; ++g) if (isValidTwist(geo, g, 1)) applyTwist(geo, state, g, 1, 1);
    const after = new Map<number, number>();
    for (const c of state) after.set(c, (after.get(c) ?? 0) + 1);
    expect([...after.entries()].sort()).toEqual([...before.entries()].sort());
  });

  it('turning every layer at once leaves it solved', () => {
    // A whole-solid rotation permutes stickers but cannot disturb the solution.
    const state = solvedState(geo);
    const all = (1 << numSlicesForGrip(geo, 0)) - 1;
    expect(isValidTwist(geo, 0, all)).toBe(true);
    applyTwist(geo, state, 0, 1, all);
    expect(isSolved(geo, state)).toBe(true);
  });

  it('scrambles to something unsolved and back again', () => {
    const state = solvedState(geo);
    const moves: { g: number; d: 1 | -1; s: number }[] = [];
    let seed = 12345;
    const next = () => (seed = (seed * 1103515245 + 12345) & 0x7fffffff);
    for (let i = 0; i < 40; ++i) {
      const g = next() % geo.nGrips;
      const d = next() % 2 === 0 ? 1 : -1;
      const s = 1 + (next() % ((1 << numSlicesForGrip(geo, g)) - 1));
      if (!isValidTwist(geo, g, s)) continue;
      moves.push({ g, d: d as 1 | -1, s });
      applyTwist(geo, state, g, d as 1 | -1, s);
    }
    expect(isSolved(geo, state)).toBe(false);
    for (const m of [...moves].reverse()) applyTwist(geo, state, m.g, -m.d as 1 | -1, m.s);
    expect(isSolved(geo, state)).toBe(true);
  });
});
