import { useEffect, useMemo, useState } from 'react';

import {
  describeShape,
  formatBytes,
  groupByFamily,
  isPlayable,
  type Catalog,
  type CatalogEntry,
} from '@mc4d/puzzle-core';

/**
 * Every puzzle the engine can build, with a picture of each.
 *
 * The classic app's picker asks two questions in sequence — which shape, then how finely sliced —
 * which is right when you are choosing one to play. This asks neither: it shows all 128 at once,
 * because the catalog is worth *browsing*. Most people do not know that a program called
 * MagicCube4D contains a 120-cell made of dodecahedra, and no menu will tell them.
 *
 * The thumbnails are renders of the real puzzles rather than illustrations, generated by
 * `tools/screenshot/gallery.mjs`. A puzzle without one still gets a card; the picture is a bonus,
 * not the point.
 */

const BASE = import.meta.env.BASE_URL;

/**
 * How the community writes a length: 3⁴ for the 3×3×3×3, 2⁴ for the pocket cube.
 *
 * The superscript is the *dimension*, not the length — 3⁴ means "three cubed, four times over", so
 * only the exponent is raised.
 */
function lengthLabel(length: number, dims: number): string {
  return `${length}${dims === 4 ? '⁴' : ''}`;
}

export function Gallery() {
  const [catalog, setCatalog] = useState<Catalog | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState('');

  useEffect(() => {
    fetch(`${BASE}assets/manifest.json`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`${r.status}`))))
      .then(setCatalog)
      .catch((e: unknown) => setError(e instanceof Error ? e.message : String(e)));
  }, []);

  // Every family has an edge length of 1 — one cubie, nothing to twist — and showing someone a
  // solved puzzle they cannot scramble is not showing them a puzzle.
  const families = useMemo(
    () =>
      catalog
        ? groupByFamily(catalog)
            .map((f) => ({ ...f, entries: f.entries.filter(isPlayable) }))
            .filter((f) => f.entries.length > 0)
        : [],
    [catalog],
  );
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return families;
    return families
      .map((f) => ({
        ...f,
        entries: f.entries.filter(
          (e) =>
            e.id.toLowerCase().includes(q) ||
            (f.name ?? '').toLowerCase().includes(q) ||
            describeShape(f.schlafli).toLowerCase().includes(q),
        ),
      }))
      .filter((f) => f.entries.length > 0);
  }, [families, query]);

  const total = useMemo(() => families.reduce((n, f) => n + f.entries.length, 0), [families]);

  return (
    <main>
      <header>
        <p className="crumb">
          <a href={BASE}>MagicCube4D</a>
        </p>
        <h1>Puzzles</h1>
        <p className="lede">
          {total || 107} puzzles, from the familiar 3×3×3×3 to a 120-cell made of dodecahedra. Pick
          one to open it in the <a href={`${BASE}classic/`}>classic app</a>.
        </p>
        <p className="lede small">
          A puzzle is a Schläfli product symbol and an edge length — nothing here is special-cased.
          The program constructs the polytope, slices it with hyperplanes, and derives the stickers
          and twist axes from what comes out.
        </p>
        <input
          type="search"
          value={query}
          placeholder="Filter by name, symbol or shape…"
          onChange={(e) => setQuery(e.target.value)}
          aria-label="Filter puzzles"
        />
      </header>

      {error && <p className="error">Could not load the catalog ({error}).</p>}
      {!catalog && !error && <p className="loading">Loading the catalog…</p>}

      {filtered.map((family) => (
        <section key={family.schlafli}>
          <h2>
            {family.name || family.schlafli}
            {family.name && <code>{family.schlafli}</code>}
          </h2>
          <p className="shape">{describeShape(family.schlafli)}</p>
          <div className="grid">
            {family.entries.map((entry) => (
              <Card key={entry.id} entry={entry} dims={4} />
            ))}
          </div>
        </section>
      ))}

      {catalog && filtered.length === 0 && <p className="loading">Nothing matches “{query}”.</p>}
    </main>
  );
}

function Card({ entry, dims }: { entry: CatalogEntry; dims: number }) {
  const [failed, setFailed] = useState(false);
  const thumb = `${BASE}gallery/${entry.path.replace(/\.mc4dpz$/, '')}.webp`;
  return (
    <a className="card" href={`${BASE}classic/#p=${encodeURIComponent(entry.id)}`}>
      <span className="shot">
        {failed ? (
          <span className="noshot" aria-hidden="true" />
        ) : (
          <img src={thumb} alt="" loading="lazy" decoding="async" onError={() => setFailed(true)} />
        )}
      </span>
      <span className="meta">
        <b>{lengthLabel(entry.length, dims)}</b>
        <span className="counts">
          {entry.nStickers.toLocaleString()} stickers · {formatBytes(entry.gzipBytes)}
        </span>
      </span>
    </a>
  );
}
